### ISSUE TITLE
Feature qualifier values wrapped across multiple lines

### ISSUE THREAD

**Issue by kbseah** [NBISweden/EMBLmyGFF3#10]
Hello,

Thanks for making a very useful tool, I'm glad to have come across it.

There is an issue I'm having with line-wrapping. EMBLmyGFF3 appears to be wrapping lines at 80 characters. This creates problems with longer qualifier values, e.g. product names, because they are broken across several lines, often in the middle of a word. When one later runs the ENA flat file validator tool with the "fix" option, it unwraps the line but adds a space, so now the unwrapped name is broken. 

Would it be possible to add an option to turn off line wrapping? Thank you!

-- Brandon

**Comment by Juke34** [comment]
It sounds a nice feature to add. We will look into it.

**Comment by Juke34** [comment]
Done - you can ow use the --no_wrap_qualifier option
