### ISSUE TITLE
When an error occurs, give information about location of error in GFF3 file

### ISSUE THREAD

**Issue by loraine-gueguen** [NBISweden/EMBLmyGFF3#12]
Thank you for this great tool! Very useful! and flexible enough to adapt to home attribute tags.
Please find below a suggestion for improvement.

Using this tool, I faced some errors with my big input GFF3 file (>300k features), e.g.:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 5: ordinal not in range(128)`
`ERROR feature: Stop codon found within the CDS. It will rise an error submiting the data to ENA. Please fix your gff file.`
`Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.`

And it was not easy to find out what character or what CDS was the wrong one in the GFF3 file. I think it would be great to provide information about the location of the error (e.g. line number, feature ID).

**Comment by Juke34** [comment]
Thank you for your feedback. That would be definitely useful, we will add this information.

**Comment by Juke34** [comment]
Done.
Will be included in the next release (not planned yet. I will wait for more modifications). To have this improvement before the next EMBLmyGFF3 release, install EMBLmyGFF3 using git clone:
```
pip uninstall EMBLmyGFF3 #could be needed twice
git clone https://github.com/NBISweden/EMBLmyGFF3.git
cd EMBLmyGFF3/
python setup.py install
```
If you already installed the tool using git clone you will have to do so:
```
pip uninstall EMBLmyGFF3 #could be needed twice
git pull  #from the EMBLmyGFF3 git repository. It will update the code
python setup.py install #from the EMBLmyGFF3 git repository
```

**Comment by loraine-gueguen** [comment]
Thanks! 
Would it be possible to catch all exceptions with a clue on the location into the GFF3 file ? The error examples number 1 and 3 in my comment above are not addressed by this commit, unless I'm mistaken (although, for error number 1, I admit that I can search for non ASCII character by a simple shell command)

**Comment by Juke34** [comment]
Actually having a CDS not multiple of three is allowed. So it is not an error, but translation method (which is part of biopython and not EMBLmyGFF3) raise a warning to inform you.

To fulfil your request I have now added an internal (in EMBLmyGFF3) Warning with the CDS ID when the CDS is not multiple of three. I'm not sure about the pertinence to add  this warning, but it is now done.

For the following error

> UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 5: ordinal not in range(128)

I don't have any test case to work with. Could you  provide me a sample of your data ?

**Comment by loraine-gueguen** [comment]
I had a look on your commit (https://github.com/NBISweden/EMBLmyGFF3/commit/6816aa85ab9a412b231b929493407208af54f213). I agree with you that this may not be pertinent to add this warning... I thought it could be possible quite easy to catch all kind of errors indifferently from biopython and provide the feature ID where it occurs, but maybe I am mistaken... I thank you anyway.

For the ASCII error, you should have the error only by copy-paste this character into an attribute of the 9th column of the GFF3: "α" (greek alpha). Tell me if not.
 
Thank you

**Comment by Juke34** [comment]
The last commit ([7398bd4](https://github.com/NBISweden/EMBLmyGFF3/commit/7398bd42ed5c5c364646dacda855fc17561c9e58)) should have addressed the UnicodeDecodeError error.
Thank you for having catched this issue.
