### ISSUE TITLE
bcbio not found

### ISSUE THREAD

**Issue by CristianRiccio** [NBISweden/EMBLmyGFF3#16]
Hi,

I've followed the instructions to install EMBLmyGFF3 with git on Mac. I got the following error:

`Download error on https://pypi.org/simple/bcbio-gff/: [Errno 54] Connection reset by peer -- Some packages may not be found!
Couldn't find index page for 'bcbio-gff' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [Errno 54] Connection reset by peer -- Some packages may not be found!
No local packages or working download links found for bcbio-gff==0.6.4
error: Could not find suitable distribution for Requirement.parse('bcbio-gff==0.6.4')`

Does this mean I have to install bcbio myself before installing EMBLmyGFF3?

Cheers.

**Comment by Juke34** [comment]
Could copy past the result of this command please ?
`pip  --version`

**Comment by CristianRiccio** [comment]
pip --version
pip 9.0.3 from /Users/user/anaconda/envs/python2env/lib/python2.7/site-packages (python 2.7)

**Comment by Juke34** [comment]
I'm wondering if the pip version could be the problem. I was using the 9.0.1. I just updated to 10.0.1 and  bcbio-gff==0.6.4 is still listed.
Try to install it by yourself with that command:
`pip install bcbio-gff==0.6.4`

If it doesn't work do:
`pip info bcbio-gff==0.6.4` to check if pip knows something about the package

otherwise update pip:
`pip install --upgrade pip`

**Comment by CristianRiccio** [comment]
pip install bcbio-gff==0.6.4 gives

`Collecting bcbio-gff==0.6.4
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/bcbio-gff/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/bcbio-gff/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/bcbio-gff/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/bcbio-gff/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/bcbio-gff/
  Could not find a version that satisfies the requirement bcbio-gff==0.6.4 (from versions: )
No matching distribution found for bcbio-gff==0.6.4`

pip info bcbio-gff==0.6.4
gives 
`ERROR: unknown command "info"`

and

`pip install --upgrade pip` gives
`Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/pip/
Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/pip/
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/pip/
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/pip/
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/pip/
Requirement already up-to-date: pip in /Users/user/anaconda/envs/python2env/lib/python2.7/site-packages`

**Comment by Juke34** [comment]
It looks like you re using a proxy and pip is unable to access data registry on the web.
Could you check you connexion and try without any proxy ?

**Comment by CristianRiccio** [comment]
I am not sure what a proxy but I am not connected through any VPN. I am on a wifi network.

**Comment by CristianRiccio** [comment]
Do you think installing it as described here would work:

https://github.com/bcbio/bcbio-nextgen

?

**Comment by Juke34** [comment]
Yes sure, but pip is made to make your life easier. So if you cannot use pip it's really a problem.

**Comment by Juke34** [comment]
I guess the easier is just to use another internet access.

**Comment by Juke34** [comment]
Maybe you have installed pip through conda. In that case try to upgrade it like that:
`conda upgrade pip`

**Comment by Juke34** [comment]
Please, let us know if you have succeeded to solve your problem.

**Comment by CristianRiccio** [comment]
I will let you know. I go back to a high-speed internet tomorrow. I'll see if that helps.

**Comment by CristianRiccio** [comment]
Hurray, everything worked this time. I got to the EMBLmyGFF3 help page. So maybe the problem was due to a slow connection. Thanks for your help.
