### ISSUE TITLE
Improve -i / --locus_tag option

### ISSUE THREAD

**Issue by loraine-gueguen** [NBISweden/EMBLmyGFF3#18]
The following points should be checked on the locus tag prefix given with option -i / --locus_tag (required when the locus-tag is registered at ENA):

> A locus tag prefix must have the following format:
> 
>     starts with a letter
>     is at least 3 characters long
>     is upper case
>     contains only alpha-numeric characters and no symbols such as -_*
>

**Comment by Juke34** [comment]
Yes I agree, I wanted to let the possibility creating an EMBL like flat file even without a proper locus_tag information. It could be useful to get an EMBL like flat file for other purpose than submission.
But tue at this point even with a fake locus_tag we could enforce the rules you emphasis.

**Comment by Juke34** [comment]
fixed by the commit d9fca3b1d206fde82dafd79b3afb43aa3ed19b0c
