### ISSUE TITLE
Update for Python 3 compliant

### ISSUE THREAD

**Issue by Juke34** [NBISweden/EMBLmyGFF3#20]
It would be nice to make the tool python 3 compliant.

**Comment by tseemann** [comment]
https://legacy.python.org/dev/peps/pep-0373/

The End Of Life date (EOL, sunset date) for Python 2.7 has been moved five years into the future, to 2020. This decision was made to clarify the status of Python 2.7 and relieve worries for those users who cannot yet migrate to Python 3. See also PEP 466.

**Comment by Juke34** [comment]
EMBLmyGFF3 is now in python3
