### ISSUE TITLE
How to avoid duplicated db_xref entries in CDS?

### ISSUE THREAD

**Issue by Rhinogradentia** [NBISweden/EMBLmyGFF3#22]
Hi,
I encountered multiple, indentical db_xref entries for CDS features with more than on exon. How can I avoid this? Do I really have to limit the db_xref information to one of multiple CDS entries of one feature in the gff file?

Thanks in advance
Best regards
Nadine

**Comment by Juke34** [comment]
Interesting it was supposed to be handled by this piece of code in feature.py

      ###########################################
      # add the value only if not already present         
      # List case
        if isinstance(value, list):
            for val in value:
                if val not in self.qualifiers[qualifier].value:
                    self.qualifiers[qualifier].add_value(val)
        # Scalar case
        else:
            if value not in self.qualifiers[qualifier].value:
                self.qualifiers[qualifier].add_value(value)

Could you copy past one example (input and output) ?
