### ISSUE TITLE
WHy can't we use biopython > 1.67 h

### ISSUE THREAD

**Issue by tseemann** [NBISweden/EMBLmyGFF3#24]
```
emblmygff3 1.2.3 has requirement biopython==1.67, but you'll have biopython 1.72 which is incompatible.
```

**Comment by hinz1** [comment]
Exactly 1.67? So I would have to downgrade my system to run your tool?

**Comment by Juke34** [comment]
You could give a try to version >1.68. If it works we can just exclude version 1.68.
If it doesn't work don't downgrade your system, use Conda instead.

**Comment by tseemann** [comment]
I agree conda envs are a solution to this, but  `25 August 2016: Biopython 1.68` is 3 years old now. Who knows what other bugs have been fixed?

**Comment by Juke34** [comment]
I agree. For our defence we use it just a little, few core methods so it guess it should not be any big difference even after many years.
We can probably use more recent version but we haven't try. I will put it in my to do list.
Anyway with the version 2 (branch feature/speedup) we should overcome this limitation.

**Comment by hinz1** [comment]
Well, we got by by installing on a machine that was rather "clean", python-wise, so installation went through and everything worked. So, thank you for publishing your work. I'll keep in mind that conda would be another way. As much as I like Python as a language, the ecosystem really is a mess. ;)

**Comment by tseemann** [comment]
What is the ETA for version 2?

**Comment by Juke34** [comment]
Early 2019 :). We have redeveloped the core of the tool to make it faster and add parallelisation, but since then we haven't HAD time to implement and test the numerous parameters we have in version 1. 
Btw I have look into detail about the issue with Biopython version >1.67, and seems finally really easy to fix. I will push a fix soon.

**Comment by tseemann** [comment]
Thanks @Juke34 !
