### ISSUE TITLE
Convert embl to gbk

### ISSUE THREAD

**Issue by Edison2021** [NBISweden/EMBLmyGFF3#29]
Hi  Jacques
Could you please add some functions to convert embl to gbk?

Best
Edison

**Comment by Juke34** [comment]
[gaas_embl2gb.pl](https://github.com/NBISweden/GAAS/blob/master/bin/gaas_embl2gb.pl) from [GAAS](https://github.com/NBISweden/GAAS) can be used. It can be installed via conda.
