### ISSUE TITLE
Problems of writing lone sequences

### ISSUE THREAD

**Issue by lufuhao** [NBISweden/EMBLmyGFF3#30]
For a 370Mb chromosome arm, it is going to take me 4-5 days to convert the the GFF3 to EMBL. The feature part was done in a few second, And then the sequence 'SQ' part takes so long time. Is it normal?

But it's very fast to write short sequences with hundreds of KB, Wonder why?

**Comment by Juke34** [comment]
Thanks for your feedback.

I'm afraid that it is actually normal.
We are aware of this compute time issue for big annotations (#6). We realised the problem a bit late when we started to work on big annotations.

We are currently working on a new version of the tool that would be much more efficient. We hope to release it beginning of next year.

**Comment by Juke34** [comment]
It should be better now in release 1.2.5, and will be much better in version 2.
