### ISSUE TITLE
Require help in mapping GFF3 type (Column3) to EMBL qualifier

### ISSUE THREAD

**Issue by VenithaB** [NBISweden/EMBLmyGFF3#36]
Hello! I have many ncRNA features (lncRNA,snoRNA,snRNA, etc.) in my GFF3 file. According to your instructions I included the following in the ```translation_gff_feature_to_embl_feature.json``` file:

``"ncRNA_gene": {``
  ``"target": "ncRNA",``
`` },``
 ``"snoRNA": {``
   ``"target": "ncRNA",``
 ``},``
 ``"lnc_RNA": {``
   ``"target": "ncRNA",``
 ``},``

I am getting a new warning saying,

``WARNING feature: The qualifier >ncRNA_class< is mandatory for the feature >ncRNA<. We will not report the feature.``

I'm not quite sure **how (and where) to add this qualifier ncRNA_class**, seeing that it changes according to feature, ie., if the feature is a lnc_RNA, then it will map to ncRNA in the EMBL file but the ncRNA_class will be lncRNA, snoRNA -> ncRNA_class:snoRNA etc.

**Comment by Juke34** [comment]
e.g https://www.ebi.ac.uk/ena/WebFeat/
You are right all type of ncRNA has to be translated to `ncRNA` **feature**. But to keep track if it was miRNA,siRNA,scRNA,lncRNA the EMBL file must contain the `ncRNA_class` **attribute**. **Feature** type in the EMBL comes from the 3rd column of the gff3 (then translated with dedicated rule contained in the translation_gff_feature_to_embl_feature.json if exists).
**Qualifier** type in the EMBL comes from the tag of the attributes (9th column). An attribute has this form: **tag=value**. So you should add in the gff3 the attribute ncRNA_class= snoRNA, ncRNA_class= lnc_RNA, etc.... accordingly.

**Comment by VenithaB** [comment]
Hi! I did as you suggested, and everything is working fine. Thank you for this tool, its really well done! Thank you also for your prompt and patient replies.
