### ISSUE TITLE
Warning regarding protein ID

### ISSUE THREAD

**Issue by VenithaB** [NBISweden/EMBLmyGFF3#37]
Hello again. I'm getting the following warning:

```WARNING feature: The value(s) ['AAEL012102-PB'] is(are) invalid for the qualifier protein_id of the feature CDS. We will not report the qualifier. (Here is the regex expected: [a-zA-Z]{3}[0-9]{5}\.[0-9]+)```

I guess the hyphen in the name is causing an issue? All the protein IDs in my GFF3 file have a hyphen and end up triggering this error (after a point the program just gets tired of them and quits printing them). I would like to preserve this information in my EMBL file, can you suggest a fix?

**Comment by Juke34** [comment]
e.g https://www.ebi.ac.uk/ena/WebFeat/ (=>CDS)
here the officical recommendation for the **protein_id**:


Qualifier | protein_id
-- | --
**Definition** | protein identifier, issued by International collaborators. this qualifier consists of a stable ID portion (accessioned data before the end of 2018 uses a 3+5 format; from the end of 2018 new accessions may be extended to a 3+7 accession format with 3 position letters and 7 numbers) plus a version number after the decimal point.
**Value Format** | <identifier>
**Example** | /protein_id="AAA12345.1"/protein_id="AAA1234567.1"
**Comment** | when the protein sequence encoded by the CDS changes, only the version number of the /protein_id value is incremented; the stable part of the /protein_id remains unchanged and as a result will permanently be associated with a given protein; this qualifier is valid only on CDS features which translate into a valid protein.

**Comment by VenithaB** [comment]
Dear Jacques,

I checked the EMBL file available for a previous assembly provided by Ensembl (available at [ftp://ftp.ensemblgenomes.org/pub/metazoa/release-44/embl/aedes_aegypti/](url)). The file contains protein IDs of the same format as in my GFF3 file. 

`FT   CDS             132625..133230`
`FT                   /gene="AAEL000117"`
`FT                   /protein_id="AAEL000117-PA"`
`FT                   /note="transcript_id=AAEL000117-RA"`
`FT                   /db_xref="RefSeq_peptide:XP_001657650.1"`
`FT                   /db_xref="RefSeq_dna:XM_001657600.1"`
`FT                   /db_xref="Uniprot/SPTREMBL:Q17Q75"`
`FT                   /db_xref="protein_id:EAT48841.1"`
`FT                   [/db_xref="UniParc:UPI0000DA8512"`]

Is there anyway to suppress/override the above warning? I am anyway looking to only transfer annotations using RATT, not sumbit to EMBL.

**Comment by Juke34** [comment]
A new parameter could be implemented to force to accept a `Qualifier` value even if it doesn't respect the specification. I'm not sure to add that. Maybe in a future release.

You can easily fix that yourself:

Uninstall EMBLmyGFF3:   

`pip unistall EMBLmyGFF3`

clone the repo in a nice place:    

```
mkdir ~/git
cd ~/git
git clone https://github.com/NBISweden/EMBLmyGFF3.git
cd EMBLmyGFF3
```

Comment  line 460 of the feature.py file and save the change (here using the nano text editor but you can use what ever you want):  
`nano EMBLmyGFF3/modules/feature.py`

install:

`python setup.py install`

or if you do not have administartive rights on your machine:

`python setup.py install --user`

**Comment by VenithaB** [comment]
Dear Jacques, 

I followed your instructions and commented out the return statement in feature.py (the 460th line). I'm still getting the same warning.

**Comment by Juke34** [comment]
The warning remains with this modification, but you should have the protein_id qualifier in the output now.

**Comment by VenithaB** [comment]
It works fine, thank you. 

I have one more question. 

11:09:16 WARNING qualifier: Unknown db_xref 'RefSeq' - skipped.

I have references to external databases that are not supported by INSDC (http://www.insdc.org/db_xref.html), eg. RefSeq, KEGG_Enzyme etc. that I would like to retain. Can I modify the legal_dbxref.json file to include the databases?

**Comment by Juke34** [comment]
Great.
Yes definitly you can do that.
