### ISSUE TITLE
EMBL flatfile not compatible with PAGIT RATT

### ISSUE THREAD

**Issue by peritob** [NBISweden/EMBLmyGFF3#39]
Thanks for the conversion software. I have a query that might be a bit off track.

I am trying to use the output .embl (1.31 GB) from augustus gff3 with RATT software (run with linux) and get this error:

`I am using the reference.fa. Please make sure that the description line of each fasta entry is the same than in the embl file name!`

Just wonder if this is a known issue?

many thanks!

**Comment by Juke34** [comment]
The EMBL file created using EMBLmyGFF3 is made for submission purpose. So there is a slight difference between the an EMBL file for submission and a released one.
One of this difference is the header of a fasta sequence that is originally:
**>sequence1**

and becomes with EMBLmyGFF3: 

> AC   XXX; 
> XX
> AC * _sequence1

I guess RATT is confused with the line `AC   XXX;`or/and the difference between the name `sequence1`and `*_sequence1`.  
In a EMBL fille released you will end with only 1 AC line with the official name retained for the sequence, most likely:

> AC sequence1

In a future version we can think to introduce an option to get an EMBL fomat "ready to use" not for submission pupose. Until then you will have to find a way to replace those line as indicated. I think it will solve the problem.

**Comment by peritob** [comment]
Thanks so much for your quick response and useful advice. I will make some changes to the file and try again with RATT.

**Comment by VenithaB** [comment]
Off-topic! 

Is this really an error? It sounds more like a heads-up. Also according to the documentation: 

> The name of each sequence in the fasta description, 
                   MUST be the same name as its corresponding embl file. So if your embl file is call Tuberculosis.embl, in your reference.fasta file, 
                   the description has to be 
                           >Tuberculsosis
                           ATTGCGTACG
                           ...

I have always interpreted that to mean that the description of each sequence in the reference .fasta file must have the same name as the .embl file.

**Comment by peritob** [comment]
Thanks VenithaB, yes I read the documentation but was still unclear where the problem in .embl was. 
Happy to close this thread now - as it is going off topic into RATT (which incidentally needs an early perl version). Thanks for all the help :)
