### ISSUE TITLE
Locus tag clarification

### ISSUE THREAD

**Issue by jimmayxu** [NBISweden/EMBLmyGFF3#4]
Hi,

Thanks for developing this tool. It would be very useful for me. 

Regarding the requirement to write the locus tag in the command (--locus_tag MY_LOCUS_TAG), do you mean the locus tag prefix, as described [here](https://www.ebi.ac.uk/ena/submit/locus-tags)? So, for _Caenorhabditis elegans_, this would be CELE because all gene features start with CELE?

**Comment by Juke34** [comment]
Hi,

Yes it is what we mean. We talk about it in the FOREWORD paragraph 

> To learn how to obtain a locus tag [click here](https://www.ebi.ac.uk/ena/submit/locus-tags).

as well as in the PARAMETER paragraph of the [Readme of the repository main page](https://github.com/NBISweden/EMBLmyGFF3).

> -i , --locus_tag | Locus tag prefix registered at ENA. More information [here](https://www.ebi.ac.uk/ena/submit/locus-tags). No default value.

But I guess the confusing may come from the internal help coming with the tool, which may be less up to date. If you could point me more precisely where it would be useful to add more precision, I would perform some updates.

I don't know if the `CELE ` locus tag is already used. ENA says `Submitters of eukaryotic and prokaryotic genomes should register a locus tag prefix prior to submitting their genome annotation into ENA.` . So if you want to submit a `Caenorhabditis elegans` genome I guess you could ask if `CELE` is still available, you will be able to use this one. If it is already used, they will provide you a new one.

**Comment by Juke34** [comment]
I have updated the "advanced help" coming with the tool. I hope it is sufficient enough.
