### ISSUE TITLE
Installation inconveniences

### ISSUE THREAD

**Issue by apredeus** [NBISweden/EMBLmyGFF3#44]
Hello all, 

thank you for your tool - very useful in dealing with EMBL/GBK/GFF3 formatting nightmare. 

I've recommended it to several people who need to do submissions of annotated genomes. One thing that makes it hard to use is the fact that most people use bioconda now - thus both python and pip are installed via conda. This breaks EMBLmyGFF3 - neither installation command specified in the readme provides a working script. If you could make it easier to install in a cluster environment, it would be great.

**Comment by Juke34** [comment]
Interesting I used it many times in conda env without any issue. Could you tell me more about the error you get? Could you tell me your env to try in similar condition (`conda env export > environment.yml` and send me the file).
We could definitely create a recipe for bioconda.

**Comment by apredeus** [comment]
Sorry, it was my bad. I missed the fact that python2 is a must for the tool. I've made an env with `conda create -n embl python=2.7`, installed the tool there, and everything works out of the box.
