### ISSUE TITLE
Joining of intron features

### ISSUE THREAD

**Issue by sophietandonnet** [NBISweden/EMBLmyGFF3#46]
Currently EMBLmyGFF3 joins intron entries. Here is an example of joined introns:

```
FT   intron          join(6625..6675,6797..6841,6924..6966,7119..7161,
FT                   7245..7286,7423..7476,7630..7673,7750..7962,8110..8158,
FT                   8225..8265,8365..8407)
FT                   /locus_tag="LOCUS1"
FT                   /note="source:AUGUSTUS"
```

As this does not make sense biologically, this issue should be fixed in later versions.

**Comment by Juke34** [comment]
Thank you for using our tool and reporting the issue.
Here for an access to a data test: https://www.biostars.org/p/403402/#403438
