### ISSUE TITLE
Error with embl file during ENA webin-cli validation  

### ISSUE THREAD

**Issue by Anto007** [NBISweden/EMBLmyGFF3#48]
Hi there,

I was trying to validate the embl files from EMBLmyGFF3 on ENA's webin-cli but I got the below error message.
 
ERROR: The qualifier "isolation_source" must exist when qualifier "environmental_sample" exists within the same feature.

I used taxid: 77133 (uncultured bacterium) at the time of running EMBLmyGFF3. To give you more of a background, I'm trying to submit a genome annotation file of an uncultivated bacterium. Any help here would be very much appreciated. Thanks in advance for your excellent support (as always!).

**Comment by Juke34** [comment]
EMBLmyGFF3 is suppose to be able to handle that. What is the command you have run?
did you use one of these options?   
--environmental_sample  
--isolation_source

**Comment by Anto007** [comment]
Many thanks for your super-quick response as always. I was using --isolation_source option but the mistake was probably that I was entering a strain name when prompted for it when I shouldn't have entered anything. I should have been paying more attention to the instructions displayed on the console. Sorry, my bad here! I will close this right away; thanks again for always being there whenever I run into issues- you're amazing!
