### ISSUE TITLE
--translate option does not work anymore

### ISSUE THREAD

**Issue by Juke34** [NBISweden/EMBLmyGFF3#53]
line 607 of feature.py has to be replaced by 
`translated_seq = str(seq.translate(codon_table)).replace('B','X').replace('Z','X').replace('J','X')`

**Comment by Jeepee8820** [comment]
Hi Jacques,

Sorry to bother you again but it seems to me that the translate option does not take into consideration the change to Met when at start. I used the parameters `--transl_table 11` and `--translate` and Webin CLI complains about `ERROR: Expected and conceptual translations are different.` The translations at these positions do indeed start with L, I or V instead of M.
Any fix possible? Thanks in advance

**Comment by Juke34** [comment]
Right good catch! If biopython deals with that it should be fixable easily otherwise I would need to implement something. Anyway, You do not need to include the translation when submitting to ENA. They will do it for you. This option is actually not really useful for submission purpose.

**Comment by Jeepee8820** [comment]
Thanks Jacques. Great to read that it's not needed to include translation when submitting to ENA.

**Comment by sanyalab** [comment]
Hi Jacques,

Will you still be including this fix for the tool? even if it is not required by ENA?

Thanks
Abhijit

**Comment by Juke34** [comment]
It is planned, but I cannot tell you when. At the latest when I will be back from parental leave in November 😁. Otherwise everyone is welcome to PR the required changes.

**Comment by sanyalab** [comment]
Hey,

Congratulations Jacques. Lovely news. Enjoy paternity leave. I'll use the
1.3 version for now. The protein translation works in that.

Thanks
Abhijit

**Comment by Juke34** [comment]
Should be fixed by now. You can try it by installing the version in the  `speed` branch.
I will soon merge it to the master branch and then release an official new version

**Comment by sanyalab** [comment]
Ok... Thank you Jacques.

I have another query w.r.t AGAT. I am using it through conda. I cannot find
"agat_sq_manage_ID
<https://github.com/NBISweden/AGAT/wiki/agat_sq_manage_ID>" in the release
0.5.0 on conda. If I download the script into the folder with the other
AGAT scripts and the conda environment, will that work?

Thanks
Abhijit

**Comment by Juke34** [comment]
Better to ask that kind of thing on the related Repo to keep the thread clear. The script is definitely in AGAT: https://github.com/NBISweden/AGAT/tree/master/bin
But the name is slightly different now `agat_sq_manage_IDs.pl`. The wiki if from an older version

**Comment by sanyalab** [comment]
> Should be fixed by now. You can try it by installing the version in the `speed` branch.
> I will soon merge it to the master branch and then release an official new version

Hi Jacques,

Is the above fix in Conda? I have the tool installed via anaconda.

Thanks
Abhijit

**Comment by Juke34** [comment]
Hi @sanyalab, I didn't merge the branch waiting for feeback from users.
If you want to use this branch just install over the emblymygff3 conda env you already have or create a new env follwing theses steps:

```
conda create -n emblmygff3_speed
conda activate emblmygff3_speed
conda --install -c bioconda emblmygff3
git clone https://github.com/NBISweden/EMBLmyGFF3.git
cd EMBLmyGFF3
git checkout speed
python setup.py install
```
Then you can use EMBLmyGFF3 normally
