### ISSUE TITLE
Is the option --locus_numbering_start working?

### ISSUE THREAD

**Issue by Jeepee8820** [NBISweden/EMBLmyGFF3#54]
Hi,

It seems to me that the` --locus_numbering_start parameter` is not working.
I provide an integer for this parameter (e.g. `--locus_numbering_start 30`) but it is not taken into consideration.
Could this be related to a 10 step increment in my gff3 input file coming from Prokka?
Thanks in advance, best

**Comment by Juke34** [comment]
Could you share your command line? 
I will have a look when I will find time.

**Comment by Juke34** [comment]
I tested with the test coming with the tool (`EMBLmyGFF3-augustus-example `). It shows the command. I added `--locus_numbering_start 30` and it works for me, I get 
```
   gene            386..13142
FT                   /locus_tag="MYLOCUSTAG_LOCUS30"
```
for the first gene and 
```
FT   gene            16086..38972
FT                   /locus_tag="MYLOCUSTAG_LOCUS31"
```
for the second...

**Comment by Jeepee8820** [comment]
Thanks for the speedy answer and this great tool.
Indeed, it works fine for me too after adapting the `EMBLmyGFF3-augustus-example` but it still fails though with the `EMBLmyGFF3-prokka-example`.

**Comment by Juke34** [comment]
Right, I guess it is because Prokka already provides a `locus_tag` attribute.
You can remove/rename it prior to run the conversion.
```
sed `s/locus_tag=/locus_tag_original=/g` yourfile.gff > yourfile_fixed.gff
```

**Comment by Jeepee8820** [comment]
Thanks this solves indeed the problem.
It would be great though to have an option for being able to set a different incremental step than 1.
