### ISSUE TITLE
Confusion with the locus tag

### ISSUE THREAD

**Issue by ptranvan** [NBISweden/EMBLmyGFF3#57]
Hi,

There are some rules for EBI about the locus tag:

https://ena-docs.readthedocs.io/en/latest/faq/locus_tags.html

I used your script to create a EMBL flat file but for each locus, `_LOCUSXX` (with `XX` a number) is added after my prefix, example : `PRE_LOCUSXX`

In their example, a locus tag would be `/locus_tag="BN5_00001"`. Therefore,  is `PRE_LOCUS` will be considered as a prefix by EBI and then refused because of this rule ?

`All characters must be alphanumeric with none such as -_*
`

**Comment by Juke34** [comment]
It should be fine, the `_LOCUSXX` suffix will be removed by the EBI submission pipeline and replaced by a proper value.
