### ISSUE TITLE
EMBL to fasta ?

### ISSUE THREAD

**Issue by ptranvan** [NBISweden/EMBLmyGFF3#59]
Hi,

Thanks for the script it works well so far. During the process some of my scaffolds have been discarded (because too short for EBI). 
Do you have a reverse script to convert the EMBL to FASTA in order for me to recompute some statistics (N50 etc.) or do you know a script that can perform directly some statistics from EMBL format ?

Best,

**Comment by Juke34** [comment]
I do not have such script and I do not know any in particular, but I'm sure you can figure out by googling.
At least N50 will not change, but might be useful for other type of statistics.

Using bioperl you can use a script similar to that one: https://github.com/NBISweden/GAAS/blob/master/bin/gaas_embl2gb.pl  replacing `-format => 'genbank'` by `-format => 'fasta'`
