### ISSUE TITLE
What the option "-a accesion" parameter should to be set(means:What type？)

### ISSUE THREAD

**Issue by Milktea-ming** [NBISweden/EMBLmyGFF3#65]
Nearly I used the [RATT-with-GFF](https://github.com/pbasting/RATT-with-GFF)(from github)
but the scrpit showed a error:
```shell
EMBLmyGFF3: error: unrecognized arguments: CM000429.1
```
The *CM000429.1* is the name of contigs
the script‘s code about *EMBLmyGFF3* as follow:
```python
#calls EMBLmyGFF3.py to convert the contig gff to an embl file
#called by main
def gffsToEmbls(contigNames):
    for contig in contigNames:
        print "\n<RATTwithGFF.py> converting "+contig+".gff to "+contig+".embl...."
        subprocess.call(["EMBLmyGFF3",\
                            "contig_gff/"+contig+".gff",\
                            "contig_fasta/"+contig+".fa",\
                            "-o", "contig_embl/"+contig+"_tmp1.embl",\
                            "-i", "tag",\
                            "-p", contig,\
                            "-s", "unknown",\
                            "-t", "linear",\
                            "-d", "STD",\
                            "-m", "genomic DNA",\
                            "-x", "UNC",\
                            "--rg","none",\
                            "-r","1",\
                            "-a",contig,\
                            "--keep_duplicates",\
                            "-q",\
                            "--shame"])
        cleanEmbl(contig)
```
What is the type of this parameter "-a accesion"?
It seems not useful when I just set a normal String like "123456" or "ABCD"
Could U tell me how to do?
Thanks a lot!

**Comment by Juke34** [comment]
Please see the README:  
https://github.com/NBISweden/EMBLmyGFF3#parameters  
or the code:  
https://github.com/NBISweden/EMBLmyGFF3/blob/f780a89d7a988ef9e3bac39391880e1610cd8b4f/EMBLmyGFF3/EMBLmyGFF3.py#L1267

It is a boolean

**Comment by Juke34** [comment]
Thank you for the feedback.
I have PR a fix to RATT-with-GFF. Let see if the owner is stll active on this project.

**Comment by CEPHAS-01** [comment]
> Please see the README: https://github.com/NBISweden/EMBLmyGFF3#parameters or the code:
> 
> https://github.com/NBISweden/EMBLmyGFF3/blob/f780a89d7a988ef9e3bac39391880e1610cd8b4f/EMBLmyGFF3/EMBLmyGFF3.py#L1267
> 
> It is a boolean, False by default putting `-a` will become true. No need to give any value

I think it is confusing in the documentation to state that the data type is Boolean when indeed there is no value to be supplied. Anyone with experience with other documentation files will naturally supply a boolean argument to that parameter. I wasted so much time on this aspect. I think it would be better understood if it stated explicitly that no value is to be supplied, rather setting the parameter or otherwise is sufficient
