### ISSUE TITLE
attribute formats broken across several lines

### ISSUE THREAD

**Issue by happy-lorna** [NBISweden/EMBLmyGFF3#68]
Hello! Thanks for the great tool.
I am trying to include some tRNA annotations in my embl file. Here is how they are formatted in the gff (with the anticodon specification matching the format as described in the webfeatures of INSDC).

##gff-version 3
NODE_1_length_526174_cov_7.912666       tRNAScan-SE     gene    489860  489943  73.2    -       .       ID=tRNA-Leu1_gene
NODE_1_length_526174_cov_7.912666       tRNAScan-SE     tRNA    489860  489943  73.2    -       .       ID=tRNA-Leu1_tRNA;product=tRNA-Leu;anticodon=(pos:489860..489943,aa:Leu,seq:CAA);Parent=tRNA-Leu1_gene

However, after I run emblmygff3, the anticodon attributes get broken across several lines, (seemingly due to the commas?) and so fail the validation. Is there a way to maintain the format of the anticodon descriptions here?

 134328 FT   gene            complement(489860..489943)
 134329 FT                   /locus_tag="PBET_LOCUS64"
 134330 FT                   /note="source:tRNAScan-SE"
 134331 FT                   /note="ID:tRNA-Leu1_gene"
 134332 FT   tRNA            complement(489860..489943)
 134333 FT                   /locus_tag="PBET_LOCUS64"
 134334 FT                   /note="source:tRNAScan-SE"
 134335 FT                   /note="ID:tRNA-Leu1_tRNA"
 134336 FT                   /anticodon="(pos:489860..489943"
 134337 FT                   /anticodon="aa:Leu"
 134338 FT                   /anticodon="seq:CAA)"
 134339 FT                   /product="tRNA-Leu"

**Comment by Juke34** [comment]
IN GFF3 an attribute can have several values separated by coma, so `(pos:489860..489943,aa:Leu,seq:CAA)`is seen as 3 values. You must quote it to be seen as one single value.

**Comment by happy-lorna** [comment]
I knew it would be something simple. Thank you so much for your help!
