### ISSUE TITLE
Use of example data

### ISSUE THREAD

**Issue by yamaton** [NBISweden/EMBLmyGFF3#69]
I'm writing an analogous conversion program for DDBJ submissions under GPL-v3.
https://github.com/yamaton/gff3toddbj

May I include your GFF3 and FASTA data from Augustus, Maker, and Prokka in my repository like [this](https://github.com/yamaton/gff3toddbj/tree/main/tests) for testing purposes? Please let me know there is any problem.

Last but not the least, thank you so much for open-sourcing your code: I have learned and borrowed a lot from your design.

**Comment by Juke34** [comment]
I guess it is fine.

I never looked into detail but DDBJ and EMBL flat files seems very similar compared to the genbank one. By curiosity, are there any strong differences that pushed you to develop this tool rather than adapt EMBLmyGFF3?

> Last but not the least, thank you so much for open-sourcing your code: I have learned and borrowed a lot from your design.

👍🏻

**Comment by yamaton** [comment]
Thanks!

I'm not a biology person, or have never submitted any to DDBJ or EMBL; just heard demands from researchers. I did not even understand what feature/qualifier translations are when I submitted the PR [#67](https://github.com/NBISweden/EMBLmyGFF3/pull/67) to be honest. So starting small was the viable option though I attempted to fork EMBLmyGFF3 in the day 1 ;)
