### ISSUE TITLE
Warning qualifier unknown db_xref

### ISSUE THREAD

**Issue by girouxem** [NBISweden/EMBLmyGFF3#71]
Hi,

The Dbxref attributes in the gff3 file are not added to the embl file even if they are from legal dbxref databases.

In a previous version from 2020, the /db_xref info was incorporated into the embl file, but not so in the latest version.

I made some edits to the EMBLmyGFF3.py and feature.py and qualifier.py - essentially rolling back a few changes related to references to the json qualifier and feature files/file paths in previous commits, and now my db_xref they are incorporated again. Maybe some other issues will surface when I look more closely at the resulting embl file, but for sure something in the last commits relating to access to the json files to update qualifiers has broken and caused those to not be imported during conversion. 

I managed to fix it for myself, so it's not really an issue for me now, but I thought I should mention that the db_xref info is not being captured into the embl files with the latest version here on github.

**Comment by Juke34** [comment]
I will investigate that once I will be back from vacation.
