### ISSUE TITLE
BioPython 1.81 installs via conda, but needs an older version

### ISSUE THREAD

**Issue by AdamStuckert** [NBISweden/EMBLmyGFF3#76]
First, thanks for this program!

I came across an install bug and I am providing the documentation + a solution.

**The bug**
I just installed via conda using the command `conda install -c bioconda emblmygff3` in a brand new, clean environment. I tried to call the program via `EMBLmyGFF3 -h` yields this error:

> ImportError: cannot import name 'UnknownSeq' from 'Bio.Seq' 

**Fix:**
Downgrade to Biopython 1.78.

**General (please complete the following information):**
- EMBLmyGFF3 version emblmygff3-2.2
- EMBLmyGFF3 installation via conda
- OS: Ubuntu

**Comment by Juke34** [comment]
Thank you for the feedback. I will update either Emblmygff3 or the conda recipe to avoid this issue.

**Comment by Juke34** [comment]
On my side I tried with different biopython version and did't get any issue (even with biopython 1.81 ). The only difference was that I used manual installation (python setup.py install), so issue maybe related to conda. I will anyway release a new conda installation version.
