### ISSUE TITLE
if I can specify certain python source during python setup.py install

### ISSUE THREAD

**Issue by njliangdong** [NBISweden/EMBLmyGFF3#77]
Hi, Mr Juke, I am glad to know if I can specifiy certain Python source when I install [EMBLmyGFF3], for example, this is best python source for me: https://pypi.tuna.tsinghua.edu.cn/simple. because always stunk at step as follow:

Installed $HOME/.pyenv/versions/3.8.6/lib/python3.8/site-packages/EMBLmyGFF3-2.2-py3.8.egg
Processing dependencies for EMBLmyGFF3==2.2
Searching for python_version>="3.8.0"
Reading https://pypi.org/simple/python_version/

waiting for your patient reply. thanks

**Comment by njliangdong** [comment]
Installation error by pip again, network not work well:
Collecting git+https://github.com/NBISweden/EMBLmyGFF3.git
  Cloning https://github.com/NBISweden/EMBLmyGFF3.git to /tmp/pip-req-build-t9m8lvli
  Running command git clone --filter=blob:none --quiet https://github.com/NBISweden/EMBLmyGFF3.git /tmp/pip-req-build-t9m8lvli
  fatal: unable to access 'https://github.com/NBISweden/EMBLmyGFF3.git/': Failed to connect to 10.31.6.91 port 80 after 130353 ms: Connection timed out
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/NBISweden/EMBLmyGFF3.git /tmp/pip-req-build-t9m8lvli did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/NBISweden/EMBLmyGFF3.git /tmp/pip-req-build-t9m8lvli did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Juke34** [comment]
python_version>="3.8.0" has to be removed from setup.py
